### ISSUE TITLE
Add support for "try" (`?`) operator

### ISSUE THREAD

**Issue by DanikVitek** [david-d-h/pipeop#1]
I'm interested if it would be possible to add support for the Rust's `?` operator so that error-prone operations could be piped also.

that would look somewhat like this:
```rs
struct Number(i32);

fn parse_number(sting: &str) -> Result<Number, Box<dyn Error>> {
    pipe!(string
        |> .parse?
        |> Number
    )
}
```
and would expand into
```rs
struct Number(i32);

fn parse_number(sting: &str) -> Result<Number, Box<dyn Error>> {
    let current = string;
    let current = call_with(|value| value.parse()?, string)?;
    let current = call_with(string, Number);
    current
}
```

**Comment by david-d-h** [comment]
I have been working on this since yesterday. I decided to rewrite the whole project, but I'm almost done. I'll update this thread when it's finished 🙏
